# Generated by Django 5.2.6 on 2025-09-19 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_created_at_alter_item_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique student admission or ID number.', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=50, verbose_name='Class')),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, help_text='This is set when the item is returned.', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_logs', to='inventory.item')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_logs', to='inventory.student')),
            ],
        ),
    ]
