# Generated by Django 5.2.6 on 2025-09-19 12:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_student_checkoutlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlog',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time the item is expected to be returned.'),
            preserve_default=False,
        ),
    ]
