# Generated by Django 5.2.6 on 2025-09-19 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_checkoutlog_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlog',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='The number of items checked out in this transaction.'),
        ),
        migrations.AddField(
            model_name='item',
            name='buffer_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Minimum quantity to keep in stock. This amount cannot be checked out.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity of this item in inventory.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
