# Generated by Django 5.2.6 on 2025-09-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_checkoutlog_quantity_item_buffer_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.PositiveIntegerField()),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('checkout_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_logs', to='inventory.checkoutlog')),
            ],
        ),
    ]
