# Generated by Django 5.2.6 on 2025-09-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_checkinlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
    ]
