# Generated by Django 5.2.6 on 2025-09-21 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_student_created_at_student_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RECEIVED', 'Received New Stock'), ('DAMAGED', 'Reported Damaged'), ('LOST', 'Reported Lost'), ('CORR_ADD', 'Manual Correction (Add)'), ('CORR_SUB', 'Manual Correction (Subtract)')], max_length=10)),
                ('quantity_change', models.IntegerField()),
                ('notes', models.TextField(blank=True, help_text='Reason for the stock change.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inventory.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
