# Generated by Django 5.2.6 on 2025-10-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_itemlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='original_section_code',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='original_space_code',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='original_section_code',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total quantity of this item in inventory.'),
        ),
    ]
