# Generated by Django 5.2.6 on 2025-10-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_item_original_section_code_item_original_space_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutlog',
            name='notes',
            field=models.TextField(blank=True, help_text='Reason or notes for this checkout.'),
        ),
    ]
