# Generated by Django 5.2.7 on 2025-10-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinlog',
            name='condition',
            field=models.CharField(choices=[('OK', 'OK'), ('DAMAGED', 'Damaged')], default='OK', help_text='The condition of the item upon return.', max_length=10),
        ),
    ]
