# Generated by Django 5.2.7 on 2025-10-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_checkinlog_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='The last time the user made a request.', null=True),
        ),
    ]
