# Generated by Django 5.2.7 on 2025-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_userprofile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, editable=False, max_length=13, null=True, unique=True),
        ),
    ]
