name: Build Sherlock Releases

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write
  artifacts: write

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller sherlock.spec

      - name: DEBUG - List contents of dist directory
        run: Get-ChildItem -Path dist -Recurse

      - name: Zip the output
        run: Compress-Archive -Path dist/Sherlock.exe -DestinationPath Sherlock-Windows.zip

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sherlock-Windows-Release
          path: Sherlock-Windows.zip

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Build with PyInstaller
        run: pyinstaller sherlock.spec

      - name: Zip the output
        run: zip -r Sherlock-Linux.zip dist/Sherlock

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: Sherlock-Linux-Release
          path: Sherlock-Linux.zip